/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewOnTVGUI.java
 *
 * Created on Oct 30, 2012, 3:21:04 PM
 */
package newontv;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author dthoma31
 */
public class NewOnTVGUI extends javax.swing.JFrame {
    
    static private LinkedList<Series> shows;

    /** Creates new form NewOnTVGUI */
    public NewOnTVGUI() {
        Cache.read();
        shows = null;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Open = new javax.swing.JFileChooser();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Save = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Add = new javax.swing.JMenuItem();
        Remove = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NewOnTV");

        Open.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Open.setPreferredSize(new java.awt.Dimension(564, 400));
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        File.setText("File");
        File.setEnabled(false);

        Save.setText("Save");
        File.add(Save);

        Menu.add(File);

        Edit.setText("Edit");
        Edit.setEnabled(false);

        Add.setText("Add show...");
        Edit.add(Add);

        Remove.setText("Remove show...");
        Edit.add(Remove);

        Menu.add(Edit);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            Open.setVisible(false);
            javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
            MainPanelLayout.removeLayoutComponent(Open);
            
            
            
            Thread r = new Thread() {
                
                @Override
                public void run() {
                    loadFile(Open.getSelectedFile());
                }
            };
            r.start();

            /*
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
            layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
            
            pack();
             */
            
        } else if (evt.getActionCommand().equals(JFileChooser.CANCEL_SELECTION)) {
            System.exit(0);
        }
    }//GEN-LAST:event_OpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new NewOnTVGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Add;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JFileChooser Open;
    private javax.swing.JMenuItem Remove;
    private javax.swing.JMenuItem Save;
    // End of variables declaration//GEN-END:variables

    private void loadFile(File file) {
        //throw new UnsupportedOperationException("Not yet implemented");
        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        JLabel Loading = new JLabel("Loading...");
        
        Loading.setVerticalAlignment(JLabel.TOP);
        Loading.setHorizontalAlignment(JLabel.LEFT);
        
        

        MainPanelLayout.setHorizontalGroup(
        MainPanelLayout.createParallelGroup().addComponent(Loading, javax.swing.GroupLayout.PREFERRED_SIZE, Open.getWidth(), javax.swing.GroupLayout.PREFERRED_SIZE));
        MainPanelLayout.setVerticalGroup(
        MainPanelLayout.createParallelGroup().addComponent(Loading, javax.swing.GroupLayout.PREFERRED_SIZE, Open.getHeight(), javax.swing.GroupLayout.PREFERRED_SIZE));
        
        
        pack();
        
        LinkedList<String> IDs = null;
        try {
            Scanner s = new Scanner(file);
            while (s.hasNextLine()) {
                if (IDs == null) {
                    IDs = new LinkedList<String>();
                }
                IDs.add(s.nextLine());
            }
            s.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewOnTVGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(1);
        }
        
        
        for (int i = 0; i < IDs.size(); i++) {
            if (shows == null) {
                shows = new LinkedList<Series>();
            }
            shows.add(new Series(IDs.get(i)));
        }
        IDs.clear();
        Loading.setVisible(false);
        MainPanelLayout.removeLayoutComponent(Loading);
        for (int i = 0; i < shows.size(); i++) {
            JLabel temp = new JLabel(i + 1 + ".  " + shows.get(i));
            
            temp.setVerticalAlignment(JLabel.TOP);
            //temp.setBounds(i * temp.getHeight(), 0, temp.getWidth(), temp.getHeight());
            temp.setHorizontalAlignment(JLabel.LEFT);
            
            


            MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup().addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, MainPanel.getWidth(), javax.swing.GroupLayout.PREFERRED_SIZE));
            MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup().addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, MainPanel.getHeight(), javax.swing.GroupLayout.PREFERRED_SIZE));
            
            
            pack();
        }
    }
}
